title: Owoeye Johnson
logo: my-new.png
description:
- ITIL V3 Foundation
- ServiceNow Certified System Administrator (CSA)
- Certified Information Auditor (CISA)
- CompTIA Linux + Certified
- Microsoft Certified Professional
- Microsoft Certified Technical Specialist
- Oracle Certified Professional
- Oracle Certified Associate


#show_downloads: true
theme: jekyll-theme-minimal
